config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  get 'home/index'
 root 'home#index'
 get 'staff' => 'home#staff'

  resources :britannia_webs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord


end

app/models/britannia_web.rb
class BritanniaWeb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
          AppointmentMailer.appointment_message(@appointment).deliver_now
          BritanniaMessagesMailer.britannia_message(@appointment).deliver_now
        format.html { redirect_to root_path, notice: 'Appointment was successfully made. You will be contacted shortly. Thank you.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:fullname, :email, :phone_number, :appointment_date, :appointment_time, :select_department)
    end
end

app/controllers/britannia_webs_controller.rb
class BritanniaWebsController < ApplicationController
  before_action :set_britannia_web, only: [:show, :edit, :update, :destroy]

  # GET /britannia_webs
  # GET /britannia_webs.json
  def index
    @britannia_webs = BritanniaWeb.all
  end

  # GET /britannia_webs/1
  # GET /britannia_webs/1.json
  def show
  end

  # GET /britannia_webs/new
  def new
    @britannia_web = BritanniaWeb.new
  end

  # GET /britannia_webs/1/edit
  def edit
  end

  # POST /britannia_webs
  # POST /britannia_webs.json
  def create
    @britannia_web = BritanniaWeb.new(britannia_web_params)

    respond_to do |format|
      if @britannia_web.save
        format.html { redirect_to @britannia_web, notice: 'Britannia web was successfully created.' }
        format.json { render :show, status: :created, location: @britannia_web }
      else
        format.html { render :new }
        format.json { render json: @britannia_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /britannia_webs/1
  # PATCH/PUT /britannia_webs/1.json
  def update
    respond_to do |format|
      if @britannia_web.update(britannia_web_params)
        format.html { redirect_to @britannia_web, notice: 'Britannia web was successfully updated.' }
        format.json { render :show, status: :ok, location: @britannia_web }
      else
        format.html { render :edit }
        format.json { render json: @britannia_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /britannia_webs/1
  # DELETE /britannia_webs/1.json
  def destroy
    @britannia_web.destroy
    respond_to do |format|
      format.html { redirect_to britannia_webs_url, notice: 'Britannia web was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_britannia_web
      @britannia_web = BritanniaWeb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def britannia_web_params
      params.require(:britannia_web).permit(:fullname, :email, :phone_number, :appointment_date, :appointment_time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @appointment = Appointment.new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/britannia_webs_helper.rb
module BritanniaWebsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :fullname %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :appointment_date %>
      <%= f.input :appointment_time %>
    <%= f.input :select_department %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Appointment date</th>
      <th>Appointment time</th>
      <th>Select department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.fullname %></td>
        <td><%= appointment.email %></td>
        <td><%= appointment.phone_number %></td>
        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.appointment_time %></td>
        <td><%= appointment.select_department %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @appointment.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appointment.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @appointment.phone_number %>
</p>

<p>
  <strong>Appointment date:</strong>
  <%= @appointment.appointment_date %>
</p>

<p>
  <strong>Appointment time:</strong>
  <%= @appointment.appointment_time %>
</p>

<p>
  <strong>Select department:</strong>
  <%= @appointment.select_department %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/britannia_webs/_form.html.erb
<%= form_with(model: britannia_web, local: true) do |form| %>
  <% if britannia_web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(britannia_web.errors.count, "error") %> prohibited this britannia_web from being saved:</h2>

      <ul>
      <% britannia_web.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, id: :britannia_web_fullname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :britannia_web_email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number, id: :britannia_web_phone_number %>
  </div>

  <div class="field">
    <%= form.label :appointment_date %>
    <%= form.datetime_select :appointment_date, id: :britannia_web_appointment_date %>
  </div>

  <div class="field">
    <%= form.label :appointment_time %>
    <%= form.datetime_select :appointment_time, id: :britannia_web_appointment_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/britannia_webs/edit.html.erb
<h1>Editing Britannia Web</h1>

<%= render 'form', britannia_web: @britannia_web %>

<%= link_to 'Show', @britannia_web %> |
<%= link_to 'Back', britannia_webs_path %>

app/views/britannia_webs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Britannia Webs</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Appointment date</th>
      <th>Appointment time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @britannia_webs.each do |britannia_web| %>
      <tr>
        <td><%= britannia_web.fullname %></td>
        <td><%= britannia_web.email %></td>
        <td><%= britannia_web.phone_number %></td>
        <td><%= britannia_web.appointment_date %></td>
        <td><%= britannia_web.appointment_time %></td>
        <td><%= link_to 'Show', britannia_web %></td>
        <td><%= link_to 'Edit', edit_britannia_web_path(britannia_web) %></td>
        <td><%= link_to 'Destroy', britannia_web, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Britannia Web', new_britannia_web_path %>

app/views/britannia_webs/new.html.erb
<h1>New Britannia Web</h1>

<%= render 'form', britannia_web: @britannia_web %>

<%= link_to 'Back', britannia_webs_path %>

app/views/britannia_webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @britannia_web.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @britannia_web.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @britannia_web.phone_number %>
</p>

<p>
  <strong>Appointment date:</strong>
  <%= @britannia_web.appointment_date %>
</p>

<p>
  <strong>Appointment time:</strong>
  <%= @britannia_web.appointment_time %>
</p>

<%= link_to 'Edit', edit_britannia_web_path(@britannia_web) %> |
<%= link_to 'Back', britannia_webs_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div align="center" id="flash" class="col-11 col-sm-3 alert alert-primary animated fadeInDown-<% if key.to_s == 'notice' %><%= 'info' %><% elsif key.to_s == 'success' %><%= 'success' %><% else key.to_s == 'danger' %><%= 'danger' %><% end %>">
        <button  aria-hidden="true" data-dismiss="alert" class="close" type="button"> × </button>
        <%= value %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Britannia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>